# Set nginx base image
FROM nginx:latest

# File Author / Maintainer
MAINTAINER Sasikumar Sugumar

RUN mkdir -p /var/www/letsencrypt/.well-known/acme-challenge
RUN mkdir -p /usr/share/nginx/html/.well-known/acme-challenge
RUN mkdir -p /var/www/sskez
RUN mkdir -p /etc/nginx/snippets
RUN mkdir -p /etc/nginx/sites-available
RUN mkdir -p /etc/letsencrypt/live/sskez.com
RUN mkdir -p /etc/nginx/sites-enabled
RUN rm /etc/nginx/conf.d/default.conf


# Copy custom configuration file from the current directory
COPY ./nginx/snippets/letsencrypt.conf /etc/nginx/snippets/letsencrypt.conf
COPY ./nginx/snippets/ssl.conf /etc/nginx/snippets/ssl.conf
COPY ./nginx/sites-available/sskez.conf  /etc/nginx/sites-available/sskez.conf
COPY ./dist /var/www/sskez

#COPY ./sskez-web/nginx/letsencrypt/live/sskez.com/fullchain.pem /etc/letsencrypt/live/sskez.com/fullchain.pem
#COPY ./sskez-web/nginx/letsencrypt/live/sskez.com/privkey.pem /etc/letsencrypt/live/sskez.com/privkey.pem

#RUN  ln -s /etc/nginx/sites-available/sskez.conf /etc/nginx/sites-enabled/sskez.conf

EXPOSE 80 443